branches:
  only:
  - master

sudo: required
language: go
env:
  - GO111MODULE=on
go:
  - 1.11.x
services:
  - docker

script:
  - go get github.com/lib/pq
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./cmd/simple/main.go
  - docker build -t dooodle/vis-simple .
  - bash install-kubectl
  - bash docker_push
  - kubectl get pods | grep mondial
  - kubectl patch deployment mondial-deployment -p   "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
  - kubectl get pods | grep mondial

